name: stremio-service
services:
  server:
    container_name: stremio-service
    restart: unless-stopped
    ports:
      - 11470:11470
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    environment:
      - NO_CORS=1
    image: stremio/server:latest
